/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import java.awt.event.ActionListener;

/**
 *
 * @author Marija
 */
public class FrmCreateFlight extends javax.swing.JFrame {

    /**
     * Creates new form FrmCreateFlight
     */
    public FrmCreateFlight() {
        initComponents();
    }
    public void addSaveBtnActionListener(ActionListener actionListener) {
        btnSave.addActionListener(actionListener);
    }
    public void addSearchAirplanesBtnActionListener(ActionListener actionListener) {
        btnSearchAirplanes.addActionListener(actionListener);
    }
    public void addSearchAirportsBtnActionListener(ActionListener actionListener) {
        btnSearchAirports.addActionListener(actionListener);
    }
    public void addSearchLinesBtnActionListener(ActionListener actionListener) {
        btnSearchLines.addActionListener(actionListener);
    }




    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSearchAirplanes = new javax.swing.JButton();
        txtAirplaneName = new javax.swing.JTextField();
        txtAirportName = new javax.swing.JTextField();
        btnSearchAirports = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirplanes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAirports = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLines = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtLine = new javax.swing.JTextField();
        btnSearchLines = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        txtAirline = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 2, 36)); // NOI18N
        jLabel1.setText("Create Flight");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        jLabel2.setText("Searh airplanes by name: ");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        jLabel3.setText("Searh airports by name: ");

        btnSearchAirplanes.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        btnSearchAirplanes.setText("Search");

        btnSearchAirports.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        btnSearchAirports.setText("Search");

        tblAirplanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAirplanes);

        tblAirports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAirports);

        tblLines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblLines);

        jLabel4.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        jLabel4.setText("Searh line by src,dest: ");

        btnSearchLines.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        btnSearchLines.setText("Search");
        btnSearchLines.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        jLabel5.setText("Date:");

        jLabel6.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        jLabel6.setText("Time:");

        jLabel7.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        jLabel7.setText("Note:");

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane4.setViewportView(txtNote);

        btnSave.setFont(new java.awt.Font("Calibri Light", 2, 24)); // NOI18N
        btnSave.setText("Save flight");

        jLabel8.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        jLabel8.setText("Airline:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchAirports))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtLine, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchLines))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSearchAirplanes))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAirline)
                                            .addComponent(txtTime)
                                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(9, 9, 9)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchAirplanes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnSearchAirports))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnSearchLines))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAirline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchAirplanes;
    private javax.swing.JButton btnSearchAirports;
    private javax.swing.JButton btnSearchLines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblAirplanes;
    private javax.swing.JTable tblAirports;
    private javax.swing.JTable tblLines;
    private javax.swing.JTextField txtAirline;
    private javax.swing.JTextField txtAirplaneName;
    private javax.swing.JTextField txtAirportName;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtLine;
    private javax.swing.JTextArea txtNote;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnSave() {
        return btnSave;
    }

    public void setBtnSave(javax.swing.JButton btnSave) {
        this.btnSave = btnSave;
    }

    public javax.swing.JButton getBtnSearchAirplanes() {
        return btnSearchAirplanes;
    }

    public void setBtnSearchAirplanes(javax.swing.JButton btnSearchAirplanes) {
        this.btnSearchAirplanes = btnSearchAirplanes;
    }

    public javax.swing.JButton getBtnSearchAirports() {
        return btnSearchAirports;
    }

    public void setBtnSearchAirports(javax.swing.JButton btnSearchAirports) {
        this.btnSearchAirports = btnSearchAirports;
    }

    public javax.swing.JButton getBtnSearchLines() {
        return btnSearchLines;
    }

    public void setBtnSearchLines(javax.swing.JButton btnSearchLines) {
        this.btnSearchLines = btnSearchLines;
    }

    public javax.swing.JTable getTblAirplanes() {
        return tblAirplanes;
    }

    public void setTblAirplanes(javax.swing.JTable tblAirplanes) {
        this.tblAirplanes = tblAirplanes;
    }

    public javax.swing.JTable getTblAirports() {
        return tblAirports;
    }

    public void setTblAirports(javax.swing.JTable tblAirports) {
        this.tblAirports = tblAirports;
    }

    public javax.swing.JTable getTblLines() {
        return tblLines;
    }

    public void setTblLines(javax.swing.JTable tblLines) {
        this.tblLines = tblLines;
    }

    public javax.swing.JTextField getTxtAirplaneName() {
        return txtAirplaneName;
    }

    public void setTxtAirplaneName(javax.swing.JTextField txtAirplaneName) {
        this.txtAirplaneName = txtAirplaneName;
    }

    public javax.swing.JTextField getTxtAirportName() {
        return txtAirportName;
    }

    public void setTxtAirportName(javax.swing.JTextField txtAirpotName) {
        this.txtAirportName = txtAirpotName;
    }

    public javax.swing.JTextField getTxtDate() {
        return txtDate;
    }

    public void setTxtDate(javax.swing.JTextField txtDate) {
        this.txtDate = txtDate;
    }

    public javax.swing.JTextField getTxtLine() {
        return txtLine;
    }

    public void setTxtLine(javax.swing.JTextField txtLine) {
        this.txtLine = txtLine;
    }

    public javax.swing.JTextField getTxtTime() {
        return txtTime;
    }

    public void setTxtTime(javax.swing.JTextField txtTime) {
        this.txtTime = txtTime;
    }

    public javax.swing.JTextField getTxtAirline() {
        return txtAirline;
    }

    public void setTxtAirline(javax.swing.JTextField txtAirline) {
        this.txtAirline = txtAirline;
    }

    public javax.swing.JTextArea getTxtNote() {
        return txtNote;
    }

    public void setTxtNote(javax.swing.JTextArea txtNote) {
        this.txtNote = txtNote;
    }
    
    
}
