/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import java.awt.event.ActionListener;

/**
 *
 * @author Marija
 */
public class FrmUserMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmUserMain
     */
    public FrmUserMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarMain = new javax.swing.JMenuBar();
        menuFlight = new javax.swing.JMenu();
        miCreateFlight = new javax.swing.JMenuItem();
        miSearchFlights = new javax.swing.JMenuItem();
        miDeleteFlight = new javax.swing.JMenuItem();
        menuLine = new javax.swing.JMenu();
        menuPassenger = new javax.swing.JMenu();
        menuCoupon = new javax.swing.JMenu();
        menuAirplane = new javax.swing.JMenu();
        menuAirport = new javax.swing.JMenu();
        menuReservation = new javax.swing.JMenu();
        miCreateReservation = new javax.swing.JMenuItem();
        miSearchReservations = new javax.swing.JMenuItem();
        miDeleteReservation = new javax.swing.JMenuItem();
        menuOptions = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFlight.setText("Flight");

        miCreateFlight.setText("Create Flight");
        menuFlight.add(miCreateFlight);

        miSearchFlights.setText("Search Flights");
        menuFlight.add(miSearchFlights);

        miDeleteFlight.setText("Delete Flight");
        menuFlight.add(miDeleteFlight);

        menuBarMain.add(menuFlight);

        menuLine.setText("Line");
        menuBarMain.add(menuLine);

        menuPassenger.setText("Passenger");
        menuBarMain.add(menuPassenger);

        menuCoupon.setText("Coupon");
        menuBarMain.add(menuCoupon);

        menuAirplane.setText("Airplane");
        menuBarMain.add(menuAirplane);

        menuAirport.setText("Airport");
        menuBarMain.add(menuAirport);

        menuReservation.setText("Reservation");

        miCreateReservation.setText("Create Reservation");
        menuReservation.add(miCreateReservation);

        miSearchReservations.setText("Search Reservations");
        menuReservation.add(miSearchReservations);

        miDeleteReservation.setText("Delete Reservation");
        menuReservation.add(miDeleteReservation);

        menuBarMain.add(menuReservation);

        menuOptions.setText("Options");

        miLogout.setText("Logout");
        menuOptions.add(miLogout);

        menuBarMain.add(menuOptions);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuAirplane;
    private javax.swing.JMenu menuAirport;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuCoupon;
    private javax.swing.JMenu menuFlight;
    private javax.swing.JMenu menuLine;
    private javax.swing.JMenu menuOptions;
    private javax.swing.JMenu menuPassenger;
    private javax.swing.JMenu menuReservation;
    private javax.swing.JMenuItem miCreateFlight;
    private javax.swing.JMenuItem miCreateReservation;
    private javax.swing.JMenuItem miDeleteFlight;
    private javax.swing.JMenuItem miDeleteReservation;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miSearchFlights;
    private javax.swing.JMenuItem miSearchReservations;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JMenuItem getMiCreateFlight() {
        return miCreateFlight;
    }

    public void setMiCreateFlight(javax.swing.JMenuItem miCreateFlight) {
        this.miCreateFlight = miCreateFlight;
    }
    

    public javax.swing.JMenuItem getMiCreateReservation() {
        return miCreateReservation;
    }

    public void setMiCreateReservation(javax.swing.JMenuItem miCreateReservation) {
        this.miCreateReservation = miCreateReservation;
    }
     public void miSearchFlightsAddActionListener(ActionListener actionListener) {
        miSearchFlights.addActionListener(actionListener);
    }
     public void miSearchReservationsAddActionListener(ActionListener actionListener) {
        miSearchReservations.addActionListener(actionListener);
    }
    
    public void miCreateFlightAddActionListener(ActionListener actionListener) {
        miCreateFlight.addActionListener(actionListener);
    }
    public void miCreateReservationAddActionListener(ActionListener actionListener) {
        miCreateReservation.addActionListener(actionListener);
    }
    
      public void miDeleteFlightAddActionListener(ActionListener actionListener) {
        miDeleteFlight.addActionListener(actionListener);
    }
    public void miDeleteReservationAddActionListener(ActionListener actionListener) {
        miDeleteReservation.addActionListener(actionListener);
    }
    public void miLogoutAddActionListener(ActionListener actionListener) {
        miLogout.addActionListener(actionListener);
    }
    public javax.swing.JMenuItem getMiSearchFlights() {
        return miSearchFlights;
    }

    public void setMiSearchFlights(javax.swing.JMenuItem miSearchFlights) {
        this.miSearchFlights = miSearchFlights;
    }

    public javax.swing.JMenuItem getMiDeleteFlight() {
        return miDeleteFlight;
    }

    public void setMiDeleteFlight(javax.swing.JMenuItem miDeleteFlight) {
        this.miDeleteFlight = miDeleteFlight;
    }

    public javax.swing.JMenuItem getMiDeleteReservation() {
        return miDeleteReservation;
    }

    public void setMiDeleteReservation(javax.swing.JMenuItem miDeleteReservation) {
        this.miDeleteReservation = miDeleteReservation;
    }

    public javax.swing.JMenuItem getMiLogout() {
        return miLogout;
    }

    public void setMiLogout(javax.swing.JMenuItem miLogout) {
        this.miLogout = miLogout;
    }

    public javax.swing.JMenuItem getMiSearchReservations() {
        return miSearchReservations;
    }

    public void setMiSearchReservations(javax.swing.JMenuItem miSearchReservations) {
        this.miSearchReservations = miSearchReservations;
    }
}
